version: '{build}'
branches:
  only:
    - master
clone_depth: 10
install:
  - SET PATH=C:\Ruby%ruby_version%\bin;%PATH%
  - ruby --version
  - gem --version
  - gem install ruby-debug-ide
  - ps: Install-Product node '8.11.3'
  - npm install
  - cd client && npm install && cd ..
  - cd server && npm install && cd ..
build_script:
  - npm run compile
test_script:
  - npm run test-debugger

environment:
  matrix:
    - ruby_version: '22'
    - ruby_version: '22-x64'
    - ruby_version: '23'
    - ruby_version: '23-x64'
    - ruby_version: '24'
    - ruby_version: '24-x64'
    - ruby_version: '25'
    - ruby_version: '25-x64'
    - ruby_version: '26'
    - ruby_version: '26-x64'
